services:
  darkroom-application:
    image: darkroom-application:latest
    container_name: darkroom-application
    networks:
      - darkroom-network
  darkroom-nginx:
    image: darkroom-nginx:latest
    container_name: darkroom-nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - darkroom-network

networks:
  darkroom-network:
    driver: bridge